SELECT IP.*, PS.PLAYING_STYLE
FROM InjuriesPlayersInformation IP
JOIN POSITION PS ON IP.PLAYER_ID = PS.PLAYER_ID
WHERE IP.GENDER = 'Male'
	AND IP.NATIONALITY = 'US'
	AND PS.PLAYING_STYLE = 'Triangle Offense';